/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillsIndexRouteImport } from './routes/bills.index'
import { Route as BillsAddRouteImport } from './routes/bills.add'
import { Route as BillsIdRouteImport } from './routes/bills.$id'
import { Route as BillsIdIndexRouteImport } from './routes/bills.$id.index'
import { Route as BillsIdEditRouteImport } from './routes/bills.$id.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIndexRoute = BillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsAddRoute = BillsAddRouteImport.update({
  id: '/bills/add',
  path: '/bills/add',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIdRoute = BillsIdRouteImport.update({
  id: '/bills/$id',
  path: '/bills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIdIndexRoute = BillsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BillsIdRoute,
} as any)
const BillsIdEditRoute = BillsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BillsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/password': typeof PasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bills/$id': typeof BillsIdRouteWithChildren
  '/bills/add': typeof BillsAddRoute
  '/bills/': typeof BillsIndexRoute
  '/bills/$id/edit': typeof BillsIdEditRoute
  '/bills/$id/': typeof BillsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/password': typeof PasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bills/add': typeof BillsAddRoute
  '/bills': typeof BillsIndexRoute
  '/bills/$id/edit': typeof BillsIdEditRoute
  '/bills/$id': typeof BillsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/password': typeof PasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bills/$id': typeof BillsIdRouteWithChildren
  '/bills/add': typeof BillsAddRoute
  '/bills/': typeof BillsIndexRoute
  '/bills/$id/edit': typeof BillsIdEditRoute
  '/bills/$id/': typeof BillsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/password'
    | '/settings'
    | '/sitemap.xml'
    | '/bills/$id'
    | '/bills/add'
    | '/bills/'
    | '/bills/$id/edit'
    | '/bills/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/password'
    | '/settings'
    | '/sitemap.xml'
    | '/bills/add'
    | '/bills'
    | '/bills/$id/edit'
    | '/bills/$id'
  id:
    | '__root__'
    | '/'
    | '/password'
    | '/settings'
    | '/sitemap.xml'
    | '/bills/$id'
    | '/bills/add'
    | '/bills/'
    | '/bills/$id/edit'
    | '/bills/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PasswordRoute: typeof PasswordRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BillsIdRoute: typeof BillsIdRouteWithChildren
  BillsAddRoute: typeof BillsAddRoute
  BillsIndexRoute: typeof BillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/': {
      id: '/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof BillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/add': {
      id: '/bills/add'
      path: '/bills/add'
      fullPath: '/bills/add'
      preLoaderRoute: typeof BillsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$id': {
      id: '/bills/$id'
      path: '/bills/$id'
      fullPath: '/bills/$id'
      preLoaderRoute: typeof BillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$id/': {
      id: '/bills/$id/'
      path: '/'
      fullPath: '/bills/$id/'
      preLoaderRoute: typeof BillsIdIndexRouteImport
      parentRoute: typeof BillsIdRoute
    }
    '/bills/$id/edit': {
      id: '/bills/$id/edit'
      path: '/edit'
      fullPath: '/bills/$id/edit'
      preLoaderRoute: typeof BillsIdEditRouteImport
      parentRoute: typeof BillsIdRoute
    }
  }
}

interface BillsIdRouteChildren {
  BillsIdEditRoute: typeof BillsIdEditRoute
  BillsIdIndexRoute: typeof BillsIdIndexRoute
}

const BillsIdRouteChildren: BillsIdRouteChildren = {
  BillsIdEditRoute: BillsIdEditRoute,
  BillsIdIndexRoute: BillsIdIndexRoute,
}

const BillsIdRouteWithChildren =
  BillsIdRoute._addFileChildren(BillsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PasswordRoute: PasswordRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BillsIdRoute: BillsIdRouteWithChildren,
  BillsAddRoute: BillsAddRoute,
  BillsIndexRoute: BillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
